[Environment]
ExecSync=[
    "/root/google-cloud-sdk/bin/gcloud auth activate-service-account 762577118557-compute@developer.gserviceaccount.com --key-file /etc/keys/gce-key.json --project cloudprojects-1164",
    "/root/google-cloud-sdk/bin/gcloud docker --authorize-only"
]
Exec=[
    "docker pull us.gcr.io/cloudprojects-1164/demo_auth",
    "docker pull us.gcr.io/cloudprojects-1164/demo_chat",
    "docker pull us.gcr.io/cloudprojects-1164/demo_db,
    "docker build -t demo_auth_test -f ./services/auth/Dockerfile_test ."
]

[Project]
RepoURL="git@github.com:cpg1111/demo-maestro-app.git"
CloneCMD="git clone"
AuthType="SSH"
SSHPrivKeyPath="~/.ssh/id_rsa"
SSHPubKeyPath="~/.ssh/id_rsa.pub"
Username="git"
Password=""
PromptForPWD=false

[[Service]]
Name="db"
Tag="0.1.1"
TagType=""
Path="./services/db"
BuildLogFilePath="/var/log/maestro/demo_db.log"
BuildCMD="docker build -t demo_db ."
TestCMD="echo 'hello'"
CheckCMD="echo 'hello'"
CreateCMD="echo 'force a build'"
UpdateCMD=""
DependsOn=[]

[[Service]]
Name="auth"
Tag="0.1.1"
TagType=""
Path="./services/auth"
BuildLogFilePath="/var/log/maestro/demo_auth.log"
BuildCMD="docker build -t demo_auth ."
TestCMD="echo 'hello'"
CheckCMD="echo 'hello'"
CreateCMD="echo 'and you get a build'"
UpdateCMD="echo 'build all the things'"
DependsOn=["db"]

[[Service]]
Name="chat"
Tag="0.1.1"
TagType=""
Path="./services/chat"
BuildLogFilePath="/var/log/maestro/demo_chat.log"
BuildCMD="docker build -t demo_chat ."
TestCMD="echo 'hello'"
CheckCMD="echo 'hello'"
CreateCMD="echo 'again'"
UpdateCMD="echo 'tri'"
DependsOn=["db"]


