$ip = ENV['VAGRANT_IP'] || "172.22.22.22"

Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-14.04" #this is the default vmware ubuntu box

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.network :private_network, ip: $ip

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "main.yml"
    end
end
